INSERT INTO FISHY_MEMBER VALUES (1, 'Vapen', 'vapen', '0417yjy@naver.com');
INSERT INTO FISHY_MEMBER VALUES (2, 'Kolibri', 'kolibri', NULL);
INSERT INTO FISHY_MEMBER VALUES (3, 'Dasnil', 'dasnil', NULL);

INSERT INTO FISHY_CURRENCY VALUES (1, 'KRW', 'W', 1);
INSERT INTO FISHY_CURRENCY VALUES (2, 'USD', '$', 1086);

INSERT INTO FISHY_BANK VALUES (1, 'Newhan Bank');

INSERT INTO FISHY_BANKACCOUNT VALUES (1, '110-123-456789', 1, 1, 1);

INSERT INTO FISHY_GROUP VALUES (1, 'hpom', 1, 2, 'head per one million');
INSERT INTO FISHY_GROUP VALUES (2, 'quarantine', 1, NULL, 'quarantine tarantino');

INSERT INTO FISHY_MEMBERGROUP VALUES (1, 1, NULL, SYSDATE, 31);
INSERT INTO FISHY_MEMBERGROUP VALUES (1, 2, NULL, SYSDATE, 31);
INSERT INTO FISHY_MEMBERGROUP VALUES (2, 1, NULL, SYSDATE, 7);
INSERT INTO FISHY_MEMBERGROUP VALUES (3, 1, NULL, SYSDATE, 1);

COMMIT;